# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  boot.loader.grub.extraEntries = ''
menuentry 'Arch Linux (on /dev/mapper/VGINT00-lvolhome)' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-29677ac8-7bac-419f-aa74-46497c26c65e' {
        insmod part_gpt
        insmod fat
        set root='hd0,gpt1'
        if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  9431-4B9D
	else
	  search --no-floppy --fs-uuid --set=root 9431-4B9D
        fi
        linux //vmlinuz-linux root=/dev/mapper/VGINT00-lvolroot rw quiet
        initrd //initramfs-linux.img
} 
'';
}
