# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "amdgpu" ];

  boot.kernelModules = [ "kvm-intel" "i2c-dev" ];

  services.xserver.enable = true;
  services.xserver.videoDrivers = [ "amdgpu" ];

  services.udev.extraRules = ''
        KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"
  '';

  hardware.opengl.driSupport32Bit = true;

  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d5bd703b-7cb2-403e-a3e8-bc92041f0e20";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9431-4B9D";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/01d94918-0f02-40c2-af54-449deb63981c";
      fsType = "ext4";
    };

  fileSystems."/home/alexvanaxe/Documents" =
    { device = "/dev/disk/by-uuid/ac0d76d3-3f2e-4d2e-8d31-bab312e8b915";
      fsType = "ext4";
    };

  fileSystems."/home/media" =
    { device = "/dev/disk/by-uuid/effd668b-b6b0-43a8-91dc-94ce2de09970";
      fsType = "ext4";
    };

  fileSystems."/home/games" =
    { device = "/dev/disk/by-uuid/c7f4bb26-7bf6-40ad-8597-1ca6e278cad2";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7f3db2a6-48ef-424c-a7ee-a2e3e97af490"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
