# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.extraModulePackages = [ ];

  services.udev.extraRules = ''
        KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"
  '';
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/00524494-fb43-40c8-a6ad-a16b6dd8e35e";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0d6bf69b-6edf-41b3-b614-625959309b85";
      fsType = "ext4";
    };

  fileSystems."/home/alexvanaxe/Documents" =
    { device = "/dev/disk/by-uuid/1b3e4b57-0bdc-4a78-bb60-78200c0858c6";
      fsType = "ext4";
    };

  fileSystems."/home/media" =
    { device = "/dev/disk/by-uuid/d1b6b1b3-c061-4222-bade-424a702118b0";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/263E-CD1F";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b5a4b0b0-abf4-4b2e-bfc1-76903a4676f7"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
